app_aiengine/urls.py
from django.urls import path
from app_aiengine import views

app_name = 'aiengine'

urlpatterns = [
    path('clustering', views.makeClusters, name = 'clustering'),
    path('recommend_players', views.recommendTeamPlayers, name='recommend_players'),
    path('selection_form', views.selectionCriteriaForm, name='selection_form'),


]

app_home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path('', views.home, name='home')
]

recommender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('app_home.urls')),
    path('accounts/', include('app_accounts.urls')),
    path('players/', include('app_players.urls')),
    path('playerselection/', include('app_playerSelection.urls')),
    path('admin/', admin.site.urls),
    path('archive/', include('app_archive.urls')),
    path('aiengine/', include('app_aiengine.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/aiengine/dfprint.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Record</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
   <script src="{% static 'home/js/jquery-3.3.1.min.js' %}"></script>
   <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
</head>
<body>

<div class="container">

  <h2>SHOWING DATAFRAMES</h2><hr><br><br>
<!--  <p>The .table-striped class adds zebra-stripes to a table:</p>            -->


  {% for table in dflist %}
    <div class="table table-striped">
      <h3>TABLE</h3>
        {% autoescape off %}{{ table }}{% endautoescape %}
    </<div>

    </div>
  {% endfor %}
</div>

</body>
</html>

templates/aiengine/selection_form.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.0.1">
  <title>Team Selection</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" type="text/css">
  <link href="{% static 'aiengine/css/selectionform.css' %}" rel="stylesheet">
</head>
<div class="container">

  <form class= "container centre-block select-form" action="{% url 'aiengine:recommend_players' %}" method='POST'>

    {% csrf_token %}

    <div class="text-center">
      <img class="mb-5" src="{% static 'home/img/ball.png' %}" alt="" width="100px">
    </div>

    <h1 class="h4 mb-4 font-weight-normal">Please Fill Below Details</h1>

    <div class="form-group">
      <!-- <label for="team1" class="col-2 col-form-label">TEAM</label> -->
      <select class="custom-select" name='team1'>
        <option value="-1" selected>Select Target Team</option>

        {% for team in teams %}
        <option value="{{team.cid}}">{{team.cname}}</option>
        {% endfor %}

      </select>
    </div>

      <div class="form-group">
        <select class="custom-select" name="team2">
          <option selected value="-1">Select Opponent Team</option>

          {% for team in teams %}
          <option value="{{team.cid}}">{{team.cname}}</option>
          {% endfor %}

        </select>
      </div>

    <div class="form-group row">
      <label for="enumber-input" class="col-3 col-form-label">Batsman</label>
      <div class="col-9">
        <input class="form-control" name="obats" type="number" value="6" id="number-input">
      </div>
    </div>

    <div class="form-group row">
      <label for="number-input2" class="col-3 col-form-label">Bowlers</label>
      <div class="col-9">
        <input class="form-control" name="obowls" type="number" value="4" id="number-input2">
      </div>
    </div>

    <div class="form-group row">
      <label for="number-input3" class="col-3 col-form-label">All-Rounders</label>
      <div class="col-9">
        <input class="form-control" name="oall" type="number" value="5" id="number-input3">
      </div>
    </div>

    <h1 class="h5 mb-4 mt-5 font-weight-normal">Select State Players</h1>

      <div class="form-group">
        <select class="custom-select" name="state-sel-method">
          <option selected value="dontselect" >Don't Select..</option>
          <option value="overall">Overall Top Players</option>
          <option value="statewise">Statewise Top Players</option>
        </select>
      </div>

    <div class="form-group row">
      <label for="example-number-input" class="col-3 col-form-label">Batsman</label>
      <div class="col-9">
        <input class="form-control" name="sbats" type="number" value="3" id="example-number-input">
      </div>
    </div>

    <div class="form-group row">
      <label for="example-number-input" class="col-3 col-form-label">Bowlers</label>
      <div class="col-9">
        <input class="form-control" name="sbowls" type="number" value="3" id="example-number-input">
      </div>
    </div>


    <div class="text-center">
      <button class="mt-5 btn btn-lg btn-primary select-btn" type="submit">Make A Selection</button>
      <p class="mt-5 mb-3 text-centre">&copy; 2020-2022</p>

    </div>

  </form>

</div>

</html>

templates/aiengine/selection_result.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" type="text/css">
  <title>Selection Result</title>
</head>
<body >

  <div class="container">

    <div class="container mt-2">
      <div class="jumbotron">
        <h1>Selection Results</h1>
        <p>List of players with ranking according to batting ang bowling innings as per your selection criteria</p>
      </div>
    </div>

    <div class="text-center">

      {% for rank, title in ranks %}

      <h1 CLASS="h4 mt-5 mb-4">Ranking According To {{title}}</h1>
      <table class="table table-hover" style="max-wigth:400px">
        <thead class="thead-dark">
        <tr class="d-flex">
          <th class="col-1">player Rank</th>
          <th class="col-2">player ID</th>
          <th class="col-6">player Name</th>
          <th class="col-3">player Team</th>
        </tr>
      </thead>

        {% for player in rank %}
        <tr class="d-flex">
          <td class="col-1">{{player.0}}</td>
          <td class="col-2">{{player.1.0}}</td>
          <td class="col-6">{{player.1.1}} {% if player.1.2 != '' %} ({{player.1.2}})  {% endif %} </td>
          <td class="col-3">{{player.1.3}}</td>
        </tr>
        {% endfor %}

      </table>
<!--{% if player.1.1 != '' %} ({{player.1.1}})  {% endif %}-->
      {% endfor %}
    </div>

  </div>

</body>
</html>